extract_task:
  description: >
    Extract all readable text from the file at {material_file}. Analyze its structure and identify key sections and points.
  expected_output: >
    A structured summary of the file's main sections and key points.
  agent: extractor

notes_task:
  description: >
    Carefully read and analyze the following extracted study material content:
    ---
    {material_text}
    ---
    Based only on this content, generate highly detailed, exam-focused notes. For each topic, provide clear explanations, step-by-step breakdowns, and examples where possible. Do not use any outside knowledge or generic information—only use what is present in the provided material.
  expected_output: >
    Markdown-formatted notes with headings, bullet points, and detailed explanations for each key topic. Include examples and clarify all important concepts, but do not add anything not found in the provided material.
  agent: note_maker
