extract_task:
  description: >
    Extract all readable text from the file at {material_file
  expected_output: >
    A structured summary of the file's main sections and key points.
  agent: extractor

notes_task:
  description: >
    Carefully read and analyze the following extracted study material content:
    ---
    {material_text}
    ---
    Only generate notes for the following section headings, and ignore all others:
    {allowed_headings}
    ---
    For each heading, extract and list only the most important points, facts, or statements exactly as they appear in the material. Do not summarize, rephrase, or make your own notes. Only include content that is directly copied from the material and is essential for exam preparation. Keep the output concise and focused on what must not be missed for the exam.
  expected_output: >
    Markdown-formatted bullet points, each copied verbatim from the material, grouped under the relevant headings. Do not add explanations, summaries, or your own words. Only include the most important, exam-critical points as they appear in the material.
  agent: note_maker
